name: "CI - Bump Version"

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  bump-version:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release-')
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout main
        uses: actions/checkout@v6
        with:
          ref: main
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Configure git user and email
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "Github Action"    

      - name: Delete Release Branch
        run: |
           echo "Deleting branch: ${{ github.head_ref }}"
           gh api -X DELETE /repos/${{ github.repository }}/git/refs/heads/${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump to the next Snapshot
        run: |
          # 1. Increment the version (e.g., 1.0.0 -> 1.0.1-SNAPSHOT)
          ./mvnw -ntp -B versions:set -DnextSnapshot=true versions:commit
          
          NEW_VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)
          
          # 2. Commit and Push
          git add pom.xml
          git commit -m "chore: Bump the project to the version: $NEW_VERSION [skip ci]"
          git push origin main