name: jitpack-build

on:
  push:
    branches: [ main ]

jobs:
  jitpack:
    runs-on: ubuntu-latest
    steps:
      - name: Request main-SNAPSHOT from JitPack
        run: |
          # timeout in 30 seconds to avoid waiting for build
          curl -s -m 30 https://jitpack.io/api/builds/com.github.snowdrop/rewrite-standalone-cli/main-SNAPSHOT/ || true
