name: "CI - Build and release"

on:
  push:
    tags:
      - 'v*' # Trigger on tags starting with v
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for the manual release (e.g. v1.0.1)'
        required: true
        default: 'v1.0.x'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
      - name: Build the uber-jar
        run: ./mvnw clean install -Dquarkus.package.type=uber-jar
      - name: Release
        uses: softprops/action-gh-release@v2
        #if: github.ref_type == 'tag'
        with:
          tag_name: ${{ github.event.inputs.tag_name || github.ref_name }}
          files: |
            target/*-runner.jar
          generate_release_notes: true
          draft: false
          prerelease: false
